---
# Image Pull Secret for internal Quay registry
apiVersion: v1
kind: Secret
metadata:
  name: netbox-image-pull-secret
  namespace: netbox
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6IHsicmVnaXN0cnkyLXF1YXktcXVheS1lbnRlcnByaXNlMi5hcHBzLmx1a2Uuc3lhbmdzYW8ubmV0L29wZW5zaGlmdCI6IHsiYXV0aCI6ICJiM0JsYm5Ob2FXWjBLM0p2WW05ME9rcERVVTFIVGxVNU4xSlpPVEEwUVVwSlVraFRUVGRFVGpORk4xZEVWVkpHUmpWUFRFUlFORVpMVVVaVVUwWk1NamMxTUZReVZ6TkxNMUJETlZvek5GST0iLCAiZW1haWwiOiAiIn19fQ==
